"""
root_id unique

Revision ID: 9e2557f5f563
Revises: 33235f55faab
Create Date: 2022-04-15 22:56:55.862349
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9e2557f5f563'
down_revision = '33235f55faab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stats_repo_id_uindex', table_name='stats')
    op.create_unique_constraint(None, 'stats', ['repo_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='unique')
    op.create_index('stats_repo_id_uindex', 'stats', ['repo_id'], unique=False)
    # ### end Alembic commands ###
